# Generated by Django 5.0.6 on 2024-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=1)),
                ('toy_donor', models.CharField(max_length=10)),
                ('applicable_age', models.IntegerField(verbose_name=10)),
                ('image_path', models.CharField(default='default_image.jpg', max_length=100)),
            ],
        ),
    ]
